---
title: "Models for Project"
author: "Tyler Pollard"
date: "2024-07-02"
header-includes:
  - \usepackage{float}
  - \usepackage{indentfirst}
  - \usepackage{caption}
  - \usepackage{array}
  - \floatplacement{figure}{H}
  - \usepackage{amsmath}
geometry: "left=1in,right=1in,top=1in,bottom=1in"
fontsize: 12pt
linestretch: 1.0
indent: true
output: pdf_document
---

```{r setup, echo = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=60), tidy = TRUE)
```

```{r load libraries}
# Load Libraries ----

```

$$
\begin{aligned}
Y_{ijk} &= \mu + \alpha_i + \beta_j + E_{ijk} \text{ where } E_{ijk} \overset{iid}\sim N(0, \sigma^2) \\
i &= 1,2 = a, \text{ for factor School}\\
j &= 1,2 = b, \text{ for factor Student} \\
k &= 1, ..., n_{ij} \text{ for \# students per group} \\
\end{aligned}
$$

\begin{table}[H]
\begin{center}
\caption*{ANOVA Table}
\begin{tabular}{c|cccc}
Source & Sum Sq & Df & F value & Pr(>F)  \\ \hline
Student & 1559.8 & 1 & 28.414 & 2.53e-07 \\
School & 8658.2 & 1 & 157.735 & < 2.2e-16 \\
Residuals & 11472.2 & 209
\end{tabular}
\end{center}
\end{table}


$$
\begin{aligned}
\(left \frac{\pi_i}{1 - \pi_i} \right) &= 1
\end{aligned}
$$

